### ISSUE TITLE
Get Travis CI running tests

### ISSUE THREAD

**Issue by drewish** [MikeTaylor/scottkit#12]
I mentioned it in https://github.com/MikeTaylor/scottkit/issues/8#issuecomment-338507797 and know you like separate issues so decided to just open one up.

**Comment by MikeTaylor** [comment]
Thanks for separating this out. I'll give it a bit of thought.

**Comment by drewish** [comment]
Cool I'll throw a PR up so you can see what it looks like. It's pretty awesome for a free product.

**Comment by MikeTaylor** [comment]
The tests need a bit of looking at.

Some of them are rather too precise in what they expect -- for example, there's a complete transcript of solving Scott Adams's _Adventureland_, which is expected to remain the same. Whenever I change anything in the output format, those tests break and need to be tediously reconfigured. (Check through the git logs, and you'll see a lot of "Rebuild regression expectations" commits.)

I think what we need is a top-level rake target that rebuilds all of the test expectations automatically, so that once we are convinced the code is code we can make an output-format change, then run `rake regenerate`, and know the tests will work.

**Comment by drewish** [comment]
Yeah the tests seemed pretty high level but I was happy there was at least something there ;)

For some reason I'd though the strings you were matching were trying to be exact matches with the original games. I didn't realize you'd customized the interface.

I did notice the [Makefile](https://github.com/MikeTaylor/scottkit/blob/master/data/test/Makefile) for updating some of it. It shouldn't be too hard to convert that to a rake task if you're interested.

**Comment by MikeTaylor** [comment]
I see we've wandered from the nominal subject of this issue -- entirely my fault! I've filed #14 to discuss regenerating tests.

BTW, I've not deliberately customised the interface: in fact I've kept the strings as close as I could to the ones ScottFree uses, which I believe would have been copied directly from the TRS-80 versions of the games. But since there was no pre-existing canonical implementation that presented the output in scrolling-dialogue form (as opposed to the standard Adam split screen) it's inevitable that it differs in some respects.

Anyway, given that the I think this one can be closed now -- do you agree?

**Comment by MikeTaylor** [comment]
I think this can be closed now that I've merged https://github.com/MikeTaylor/scottkit/pull/13 -- do you agree?

**Comment by drewish** [comment]
Yeah I think this is sufficient. Only follow up might be to change the github config to not allow merged with out passing tests. To prevent situations like my other PR ;)

**Comment by MikeTaylor** [comment]
Do you know how to make that change? (I know little to nothing about Travis.)

**Comment by drewish** [comment]
Sure thing, hit up https://github.com/MikeTaylor/scottkit/settings/branches/master and check the following boxes:
![10_23_17__9_23_am](https://user-images.githubusercontent.com/68750/31897506-cef5a94a-b7d3-11e7-82fc-e678fa9844e0.png)

You can decide if you want to require it for your own PR, I usually do on my own projects just to avoid mistakes.

**Comment by MikeTaylor** [comment]
Weird -- when I do this, it says it can't find an any status-checks to enforce. Any ideas?
![screen shot 2017-10-23 at 16 26 57](https://user-images.githubusercontent.com/212761/31897748-384a831c-b80f-11e7-8e5d-c03ce56fabf7.png)

**Comment by drewish** [comment]
Oh right, yeah sorry forgot you hadn't enabled travis yet. Easiest way is to hit up https://travis-ci.org and use the sign in with GitHub button at the top. Once you grant access it should give you a list of your repos and switches to enable it. Flip the switch for the scottkit repo and it'll add web hooks to the GitHub repo and start running the tests and reporting status on the PRs.

**Comment by MikeTaylor** [comment]
Thanks, appreciated! It's nice that this process has had the side-effect of introducing me to Travis :-)

**Comment by MikeTaylor** [comment]
Well, I've seen tests running on a commit now! https://travis-ci.org/MikeTaylor/scottkit/builds/291618414

But of course they're all failing :-(

I'll wait for you to fix the output order to conform to what's expected.

**Comment by drewish** [comment]
Great, I'll get you a PR for that this evening

**Comment by MikeTaylor** [comment]
Beautiful!

**Comment by drewish** [comment]
For the historical record: https://github.com/MikeTaylor/scottkit/pull/15
